export const EDITED_USER_SCORE = 'EDITED_USER_SCORE';

export const ADDED_NEW_USER = 'ADDED_NEW_USER';

export const FETCHED_USERS = 'FETCHED_USERS';

export const FETCH_FAILED = 'FETCH_FAILED';

export const FETCH_NEW_USERS = 'FETCH_NEW_USERS';

export const PAGINATE_USERS = 'PAGINATE_USERS';
